services:
  database:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=example
    ports:
      - 5432:5432
  redis:
    image: docker.io/redis:6.2.6-alpine3.15
    ports:
      - "6379:6379"
